apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-sentinel
  template:
    metadata:
      labels:
        app: pipeline-sentinel
    spec:
      containers:
      - name: pipeline-sentinel
        image: pipeline-sentinel:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-sentinel
spec:
  selector:
    app: pipeline-sentinel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
